# Generated by Django 5.2.3 on 2025-06-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edicao',
            name='imagem',
            field=models.URLField(),
        ),
    ]
