# Generated by Django 5.2.3 on 2025-06-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_edicao_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destaques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.URLField()),
                ('link', models.URLField()),
                ('ordem', models.IntegerField(default=0)),
            ],
        ),
    ]
