# Generated by Django 5.2.3 on 2025-06-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_destaques'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outros_grupos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.URLField()),
                ('descricao', models.CharField(max_length=100)),
                ('ordem', models.IntegerField(default=0)),
            ],
        ),
    ]
