# Generated by Django 5.2.3 on 2025-06-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_outros_grupos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outros_grupos',
            name='descricao',
            field=models.TextField(max_length=100),
        ),
    ]
