# Generated by Django 5.2.3 on 2025-06-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_outros_grupos_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outros_grupos',
            name='descricao',
            field=models.TextField(),
        ),
    ]
