services:
  - type: web
    name: meu-site-django
    env: python
    buildCommand: ""
    startCommand: gunicorn jornal_iam.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: jornal_iam.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
    staticPublishPath: staticfiles
